### ISSUE TITLE
require(D:\xamppnew\htdocs\sfa\dabur\dabur-sfa-new-admin\vendor\milantarami\nepali-calendar\src./../config/nepali-calendar.php): Failed to open stream: Permission denied

### ISSUE THREAD

**Issue by 0xyzone** [milantarami/nepali-calendar#12]
![image](https://github.com/milantarami/nepali-calendar/assets/58982560/e7d1d8ef-6269-44ee-b022-de8983190a30)

**Comment by milantarami** [comment]
try running `xammp` as an administrator mode

**Comment by SubashPds** [comment]
I faced same problem 
  require(D:\hrm\vendor\milantarami\nepali-calendar\src./../config/nepali-calendar.php): Failed to open stream: Permission denied

**Comment by SubashPds** [comment]
> try running `xammp` as an administrator mode

Not worked for me

**Comment by milantarami** [comment]
@SubashPds @0xyzone  Please check with a latest version v1.4.1 i have released  and let me know if problem exists you can reopen this issue and i am closing for now
