### ISSUE TITLE
Nepali to English Date conversion is wrong

### ISSUE THREAD

**Issue by sandysh** [milantarami/nepali-calendar#13]
I have been using your package in an accounting system and i found that Nepali to ENG date conversion has mistakes in some date conversions. For reference i am sending you the Nepali date and converted english date which is wrong. Can you please check into this.

Nepali Date: 2080-03-31

Converted Eng Date: 2023-08-06

which is wrong, 

converted date should be: 2023-07-16

**Comment by milantarami** [comment]
i had rechecked a date conversion for date` (2080-03-01) BS ` which i got a correct conversion  `2023-07-16 AD` using a latest version of this package.

can you show me a code snippet for your version of implementation.

**Comment by milantarami** [comment]
This issue is closed due to insufficient information. You can repoen it if same problem exists.
