### ISSUE TITLE
Can we use this package on Laravel 8?

### ISSUE THREAD

**Issue by dipenchand** [milantarami/nepali-calendar#9]
I'm trying to use this package in Laravel 8, but its giving following Error:
```
$ php artisan vendor:publish --tag=nepali-calendar-config

Can't locate path: </Users/dipenchand/Documents/dev/mlogics/freedom-php/backend/vendor/milantarami/nepali-calendar/src./../config/nepali-calendar.php>
Publishing complete.
```

**Comment by milantarami** [comment]
I had just tested with a fresh installation of laravel 8 and is works as expected.  Unfortunately there isn't much I can go on with the information you've provided. 

try clearing cache **php artisan optimize:clear**

and reinstalling it

**Comment by milantarami** [comment]
you can reopen this issue if it is not solved!
